apiVersion: v1
kind: Service
metadata:
  name: misakif-blog
  namespace: namespace-workflow-1715402491197
spec:
  type: LoadBalancer
  selector:
    app: misakif-blog
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
